-- H2 test stub for Phase 6 migration.
-- Omits PL/pgSQL triggers; uses IDENTITY PKs; DECIMAL for money (H2 dialect).

CREATE TABLE appeals (
    id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id                INTEGER         NOT NULL REFERENCES claims(id),
    member_id               INTEGER         NOT NULL REFERENCES members(id),
    appeal_type             VARCHAR(10)     NOT NULL,
    submitted_date          DATE            NOT NULL,
    deadline_date           DATE            NOT NULL,
    status                  VARCHAR(15)     NOT NULL DEFAULT 'OPEN',
    assigned_to             INTEGER         REFERENCES users(id),
    resolved_date           DATE,
    outcome                 VARCHAR(10),
    outcome_notes           TEXT,
    submitted_by_user_id    INTEGER         REFERENCES users(id),
    created_at              TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE subrogation_cases (
    id              INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id        INTEGER         NOT NULL REFERENCES claims(id),
    opened_date     DATE            NOT NULL,
    status          VARCHAR(15)     NOT NULL DEFAULT 'OPEN',
    liable_party    VARCHAR(200),
    recovery_amount DECIMAL(12,2),
    notes           TEXT,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uq_subrogation_claim ON subrogation_cases (claim_id);

CREATE TABLE payment_batches (
    id              INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_date      DATE            NOT NULL,
    total_amount    DECIMAL(12,2)   NOT NULL DEFAULT 0.00,
    status          VARCHAR(15)     NOT NULL DEFAULT 'PENDING',
    exported_at     TIMESTAMP,
    file_reference  VARCHAR(200),
    created_by      INTEGER         REFERENCES users(id),
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

ALTER TABLE payments ADD COLUMN batch_id INTEGER REFERENCES payment_batches(id);

CREATE TABLE scheduled_job_log (
    id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name            VARCHAR(100)    NOT NULL,
    started_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    completed_at        TIMESTAMP,
    status              VARCHAR(10)     NOT NULL DEFAULT 'RUNNING',
    records_processed   INTEGER         NOT NULL DEFAULT 0,
    error_message       TEXT
);

CREATE TABLE claims_archive (
    id              INTEGER         NOT NULL PRIMARY KEY,
    claim_number    VARCHAR(30)     NOT NULL,
    member_id       INTEGER         NOT NULL,
    provider_id     INTEGER         NOT NULL,
    claim_type      VARCHAR(15)     NOT NULL,
    original_claim_id INTEGER,
    date_of_service DATE            NOT NULL,
    submission_date DATE            NOT NULL,
    status          VARCHAR(20)     NOT NULL,
    plan_id         INTEGER         NOT NULL,
    coverage_order  VARCHAR(10)     NOT NULL,
    denial_reason_code VARCHAR(50),
    notes           TEXT,
    archived_at     TIMESTAMP       NOT NULL DEFAULT NOW()
);
