-- H2 test stub for Phase 9 migration.
-- Omits PL/pgSQL triggers; uses IDENTITY PKs; H2 syntax for constraints.

CREATE TABLE claim_intake_batches (
    id               INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name        VARCHAR(255)    NOT NULL,
    file_hash        VARCHAR(64)     NOT NULL,
    status           VARCHAR(20)     NOT NULL DEFAULT 'PROCESSING',
    total_records    INTEGER         NOT NULL DEFAULT 0,
    succeeded        INTEGER         NOT NULL DEFAULT 0,
    quarantined      INTEGER         NOT NULL DEFAULT 0,
    error_message    TEXT,
    created_at       TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_intake_file_hash UNIQUE (file_hash),
    CONSTRAINT ck_intake_status CHECK (status IN ('PROCESSING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX idx_intake_batches_status ON claim_intake_batches (status);

-- NOTE: the production V12 migration also seeds the 'system' batch-actor user.
-- The H2 test stub deliberately does NOT seed it: no DAO integration test reads
-- that row (IntakeService resolves the system user via a mocked UserDAO in unit
-- tests), and seeding an explicit-id user here would contaminate H2's shared
-- in-JVM IDENTITY sequence for the users table, colliding with other DaoIT
-- fixtures that insert users with low explicit ids.
