-- H2 test stub for Phase 12 migration.
-- Omits the PL/pgSQL trigger; uses IDENTITY PK; H2 syntax for constraints.

CREATE TABLE edi_transactions (
    id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direction               VARCHAR(10)     NOT NULL,
    transaction_type        VARCHAR(10)     NOT NULL,
    isa_control_number      VARCHAR(20),
    gs_control_number       VARCHAR(20),
    st_control_number       VARCHAR(20),
    status                  VARCHAR(20)     NOT NULL,
    related_transaction_id  INTEGER         REFERENCES edi_transactions(id),
    file_reference          VARCHAR(255),
    detail                  TEXT,
    created_at              TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_edi_txn_direction CHECK (direction IN ('INBOUND', 'OUTBOUND')),
    CONSTRAINT ck_edi_txn_status CHECK (status IN ('ACCEPTED', 'REJECTED', 'PARTIAL'))
);

CREATE INDEX idx_edi_transactions_isa ON edi_transactions (isa_control_number);
CREATE INDEX idx_edi_transactions_related ON edi_transactions (related_transaction_id);
CREATE INDEX idx_edi_transactions_created_at ON edi_transactions (created_at);
