-- H2 test stub for Phase 13 migration.
-- Omits the PL/pgSQL trigger; uses IDENTITY PK; H2 syntax for constraints.

CREATE TABLE trading_partners (
    id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_name            VARCHAR(100)    NOT NULL,
    isa_qualifier           VARCHAR(2)      NOT NULL,
    isa_id                  VARCHAR(15)     NOT NULL,
    gs_id                   VARCHAR(15)     NOT NULL,
    enabled_transactions    VARCHAR(200),
    transport_type          VARCHAR(10)     NOT NULL DEFAULT 'LOCAL',
    transport_host          VARCHAR(255),
    transport_port          INTEGER,
    transport_username      VARCHAR(100),
    transport_credential_ref VARCHAR(200),
    inbound_path            VARCHAR(500),
    outbound_path           VARCHAR(500),
    active                  BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_trading_partner_transport CHECK (transport_type IN ('LOCAL', 'SFTP'))
);

CREATE INDEX idx_trading_partners_active ON trading_partners (active);

ALTER TABLE edi_transactions ADD COLUMN trading_partner_id INTEGER REFERENCES trading_partners(id);
CREATE INDEX idx_edi_transactions_trading_partner ON edi_transactions (trading_partner_id);
