-- H2 test stub for Phase 16 migration.
-- Omits the PL/pgSQL trigger; uses IDENTITY PK; H2 syntax for constraints.

CREATE TABLE eligibility_checks (
    id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id           INTEGER         NOT NULL REFERENCES members(id),
    provider_id         INTEGER         REFERENCES providers(id),
    service_type        VARCHAR(50),
    inquiry_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    response_at         TIMESTAMP,
    result_status       VARCHAR(20)     NOT NULL,
    coverage_snapshot   TEXT,
    checked_by_user_id  INTEGER         REFERENCES users(id),
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_eligibility_result_status CHECK (result_status IN ('ACTIVE', 'INACTIVE', 'ERROR'))
);

CREATE INDEX idx_eligibility_checks_member ON eligibility_checks (member_id);
CREATE INDEX idx_eligibility_checks_inquiry_at ON eligibility_checks (inquiry_at);
