-- H2 test stub for Phase 17 migration.
-- Omits the PL/pgSQL trigger; uses IDENTITY PK; H2 syntax for constraints.

CREATE TABLE enrollment_batches (
    id               INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name        VARCHAR(255)    NOT NULL,
    file_hash        VARCHAR(64)     NOT NULL,
    status           VARCHAR(20)     NOT NULL DEFAULT 'PROCESSING',
    total_records    INTEGER         NOT NULL DEFAULT 0,
    succeeded        INTEGER         NOT NULL DEFAULT 0,
    quarantined      INTEGER         NOT NULL DEFAULT 0,
    error_message    TEXT,
    created_at       TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_enrollment_file_hash UNIQUE (file_hash),
    CONSTRAINT ck_enrollment_status CHECK (status IN ('PROCESSING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX idx_enrollment_batches_status ON enrollment_batches (status);
