-- H2 test stub for Phase 18 migration.
-- Omits the PL/pgSQL trigger; uses IDENTITY PK; H2 syntax for constraints.

ALTER TABLE providers ADD COLUMN ach_routing_number VARCHAR(9);
ALTER TABLE providers ADD COLUMN ach_account_number VARCHAR(17);
ALTER TABLE providers ADD COLUMN ach_account_type VARCHAR(10);

ALTER TABLE providers ADD CONSTRAINT ck_provider_ach_account_type
    CHECK (ach_account_type IS NULL OR ach_account_type IN ('CHECKING', 'SAVINGS'));

CREATE TABLE eft_payments (
    id                       INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_batch_id         INTEGER         NOT NULL REFERENCES payment_batches(id),
    remittance_batch_id      INTEGER         NOT NULL REFERENCES remittance_batches(id),
    trn_reassociation_number VARCHAR(30)     NOT NULL,
    amount                   NUMERIC(12,2)   NOT NULL,
    settlement_status        VARCHAR(20)     NOT NULL DEFAULT 'GENERATED',
    ach_file_reference       VARCHAR(255),
    entry_count              INTEGER         NOT NULL DEFAULT 0,
    skipped_provider_count   INTEGER         NOT NULL DEFAULT 0,
    created_at               TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_eft_payment_batch UNIQUE (payment_batch_id),
    CONSTRAINT ck_eft_settlement_status CHECK (settlement_status IN ('GENERATED', 'SETTLED', 'FAILED'))
);

CREATE INDEX idx_eft_payments_batch ON eft_payments (payment_batch_id);
