-- H2 test stub for Phase 3 migration.
-- Creates all tables; omits PL/pgSQL triggers (H2 JDBC mode can't parse them)
-- and replaces ON CONFLICT DO NOTHING with plain INSERTs (H2 1.4 syntax).

CREATE TABLE members (
    id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_number       VARCHAR(20)     NOT NULL,
    first_name          VARCHAR(100)    NOT NULL,
    last_name           VARCHAR(100)    NOT NULL,
    dob                 DATE            NOT NULL,
    address             VARCHAR(255),
    phone               VARCHAR(20),
    email               VARCHAR(150),
    status              VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    deleted_at          TIMESTAMP,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE providers (
    id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npi                 VARCHAR(10)     NOT NULL,
    name                VARCHAR(200)    NOT NULL,
    provider_type       VARCHAR(20)     NOT NULL DEFAULT 'INDIVIDUAL',
    specialty           VARCHAR(100),
    network_status      VARCHAR(20)     NOT NULL DEFAULT 'IN_NETWORK',
    phone               VARCHAR(20),
    address             VARCHAR(255),
    deleted_at          TIMESTAMP,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE plans (
    id                          INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_name                   VARCHAR(200)    NOT NULL,
    plan_type                   VARCHAR(10)     NOT NULL,
    deductible_amount           DECIMAL(12,2)   NOT NULL DEFAULT 0.00,
    oop_max                     DECIMAL(12,2)   NOT NULL DEFAULT 0.00,
    copay_amount                DECIMAL(12,2)   NOT NULL DEFAULT 0.00,
    coverage_pct_in_network     DECIMAL(5,2)    NOT NULL DEFAULT 80.00,
    coverage_pct_out_network    DECIMAL(5,2)    NOT NULL DEFAULT 60.00,
    benefit_year_start          DATE            NOT NULL DEFAULT '2026-01-01',
    timely_filing_days          INTEGER         NOT NULL DEFAULT 180,
    deleted_at                  TIMESTAMP,
    created_at                  TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE plan_coverage_rules (
    id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id             INTEGER         NOT NULL REFERENCES plans(id),
    service_type        VARCHAR(50)     NOT NULL,
    coverage_pct        DECIMAL(5,2)    NOT NULL DEFAULT 80.00,
    requires_referral   BOOLEAN         NOT NULL DEFAULT FALSE,
    requires_prior_auth BOOLEAN         NOT NULL DEFAULT FALSE
);

CREATE TABLE member_coverage (
    id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id           INTEGER         NOT NULL REFERENCES members(id),
    plan_id             INTEGER         NOT NULL REFERENCES plans(id),
    coverage_order      VARCHAR(10)     NOT NULL,
    effective_date      DATE            NOT NULL,
    termination_date    DATE,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE fee_schedule_rates (
    id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id             INTEGER         NOT NULL REFERENCES plans(id),
    provider_id         INTEGER         REFERENCES providers(id),
    procedure_code      VARCHAR(10)     NOT NULL,
    allowed_amount      DECIMAL(12,2)   NOT NULL,
    effective_date      DATE            NOT NULL,
    termination_date    DATE,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE prior_authorizations (
    id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id           INTEGER         NOT NULL REFERENCES members(id),
    provider_id         INTEGER         NOT NULL REFERENCES providers(id),
    procedure_code      VARCHAR(10)     NOT NULL,
    service_type        VARCHAR(50),
    authorized_from     DATE            NOT NULL,
    authorized_to       DATE            NOT NULL,
    auth_number         VARCHAR(50)     NOT NULL,
    status              VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    approved_units      INTEGER         NOT NULL DEFAULT 1,
    notes               TEXT,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE referrals (
    id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id               INTEGER         NOT NULL REFERENCES members(id),
    referring_provider_id   INTEGER         NOT NULL REFERENCES providers(id),
    referred_to_provider_id INTEGER         NOT NULL REFERENCES providers(id),
    service_type            VARCHAR(50)     NOT NULL,
    valid_from              DATE            NOT NULL,
    valid_to                DATE            NOT NULL,
    referral_number         VARCHAR(50)     NOT NULL,
    status                  VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    notes                   TEXT,
    created_at              TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE denial_reason_codes (
    code        VARCHAR(50)  PRIMARY KEY,
    carc_code   VARCHAR(10),
    description VARCHAR(500) NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE procedure_codes (
    code        VARCHAR(50)  PRIMARY KEY,
    description VARCHAR(500) NOT NULL,
    service_type VARCHAR(50),
    active      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE diagnosis_codes (
    code        VARCHAR(50)  PRIMARY KEY,
    description VARCHAR(500) NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE service_type_categories (
    code        VARCHAR(100) PRIMARY KEY,
    description VARCHAR(200) NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE
);

INSERT INTO service_type_categories (code, description) VALUES ('OFFICE_VISIT', 'Office / Outpatient Visit');
INSERT INTO service_type_categories (code, description) VALUES ('PREVENTIVE', 'Preventive Care');
INSERT INTO service_type_categories (code, description) VALUES ('SPECIALIST', 'Specialist Consultation');
INSERT INTO service_type_categories (code, description) VALUES ('EMERGENCY', 'Emergency Services');
INSERT INTO service_type_categories (code, description) VALUES ('URGENT_CARE', 'Urgent Care');
INSERT INTO service_type_categories (code, description) VALUES ('INPATIENT', 'Inpatient Hospitalization');
INSERT INTO service_type_categories (code, description) VALUES ('OUTPATIENT', 'Outpatient Surgery / Procedure');
INSERT INTO service_type_categories (code, description) VALUES ('MENTAL_HEALTH', 'Mental Health / Behavioral Health');
INSERT INTO service_type_categories (code, description) VALUES ('LABORATORY', 'Laboratory / Pathology');
INSERT INTO service_type_categories (code, description) VALUES ('IMAGING', 'Radiology / Imaging');
INSERT INTO service_type_categories (code, description) VALUES ('OTHER', 'Other / Miscellaneous');

INSERT INTO denial_reason_codes (code, carc_code, description) VALUES ('TIMELY_FILING', '29', 'The time limit for filing has expired');
INSERT INTO denial_reason_codes (code, carc_code, description) VALUES ('NOT_ELIGIBLE', '26', 'Expenses incurred prior to coverage');
INSERT INTO denial_reason_codes (code, carc_code, description) VALUES ('DUPLICATE', '18', 'Exact duplicate claim or service');
INSERT INTO denial_reason_codes (code, carc_code, description) VALUES ('NOT_COVERED', '96', 'Non-covered charge(s)');
INSERT INTO denial_reason_codes (code, carc_code, description) VALUES ('NO_PRIOR_AUTH', '197', 'Precertification/authorization/notification absent');
