-- H2 test stub for Phase 4 migration.
-- Omits PL/pgSQL triggers; uses IDENTITY PKs; DECIMAL for money.
-- Plain INSERTs instead of INSERT ... WHERE NOT EXISTS (H2 syntax).

CREATE TABLE claims (
    id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_number            VARCHAR(30)     NOT NULL UNIQUE,
    member_id               INTEGER         NOT NULL REFERENCES members(id),
    provider_id             INTEGER         NOT NULL REFERENCES providers(id),
    claim_type              VARCHAR(15)     NOT NULL,
    original_claim_id       INTEGER         REFERENCES claims(id),
    date_of_service         DATE            NOT NULL,
    submission_date         DATE            NOT NULL,
    status                  VARCHAR(20)     NOT NULL DEFAULT 'SUBMITTED',
    plan_id                 INTEGER         NOT NULL REFERENCES plans(id),
    coverage_order          VARCHAR(10)     NOT NULL,
    prior_auth_number       VARCHAR(50),
    referral_number         VARCHAR(50),
    cob_primary_paid        DECIMAL(12,2),
    accident_indicator      BOOLEAN         NOT NULL DEFAULT FALSE,
    accident_type           VARCHAR(20),
    accident_date           DATE,
    denial_reason_code      VARCHAR(50)     REFERENCES denial_reason_codes(code),
    notes                   TEXT,
    assigned_to_user_id     INTEGER         REFERENCES users(id),
    created_by_user_id      INTEGER         REFERENCES users(id),
    status_entered_at       TIMESTAMP,
    version                 INTEGER         NOT NULL DEFAULT 0,
    created_at              TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE claim_diagnoses (
    id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id            INTEGER         NOT NULL REFERENCES claims(id),
    diagnosis_code      VARCHAR(50)     NOT NULL,
    sequence_number     INTEGER         NOT NULL,
    diagnosis_type      VARCHAR(10)     NOT NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE claim_line_items (
    id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id                INTEGER         NOT NULL REFERENCES claims(id),
    procedure_code          VARCHAR(50)     NOT NULL,
    description             VARCHAR(500),
    billed_amount           DECIMAL(12,2)   NOT NULL,
    allowed_amount          DECIMAL(12,2),
    plan_paid_amount        DECIMAL(12,2),
    member_responsibility   DECIMAL(12,2),
    deductible_applied      DECIMAL(12,2)   NOT NULL DEFAULT 0.00,
    copay_applied           DECIMAL(12,2)   NOT NULL DEFAULT 0.00,
    rate_source             VARCHAR(30),
    adjustment_reason_code  VARCHAR(50),
    created_at              TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE deductible_accumulators (
    id                          INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id                   INTEGER         NOT NULL REFERENCES members(id),
    plan_id                     INTEGER         NOT NULL REFERENCES plans(id),
    benefit_year_start          DATE            NOT NULL,
    deductible_accumulated      DECIMAL(12,2)   NOT NULL DEFAULT 0.00,
    oop_accumulated             DECIMAL(12,2)   NOT NULL DEFAULT 0.00,
    updated_at                  TIMESTAMP       NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_deductible_acc UNIQUE (member_id, plan_id, benefit_year_start)
);

-- NOTE: reflects the post-V7 end-state — NO UNIQUE(claim_id). Re-adjudication retains history
-- by inserting a new contribution row per run (prod V7__contribution_per_run.sql drops the
-- original UNIQUE constraint; the H2 stub simply never creates it).
CREATE TABLE claim_accumulator_contributions (
    id                          INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id                    INTEGER         NOT NULL REFERENCES claims(id),
    benefit_year_start          DATE            NOT NULL,
    deductible_contributed      DECIMAL(12,2)   NOT NULL,
    oop_contributed             DECIMAL(12,2)   NOT NULL,
    reversed                    BOOLEAN         NOT NULL DEFAULT FALSE,
    applied_at                  TIMESTAMP       NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_contrib_claim ON claim_accumulator_contributions (claim_id);

CREATE TABLE adjudication_results (
    id              INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id        INTEGER         NOT NULL REFERENCES claims(id),
    run_id          INTEGER         NOT NULL DEFAULT 1,
    step_number     INTEGER         NOT NULL,
    rule_name       VARCHAR(50)     NOT NULL,
    rule_type       VARCHAR(10)     NOT NULL,
    passed          BOOLEAN         NOT NULL,
    reason          VARCHAR(500),
    evaluated_at    TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE claim_audit (
    id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id                INTEGER         NOT NULL REFERENCES claims(id),
    event_type              VARCHAR(50)     NOT NULL,
    old_status              VARCHAR(20),
    new_status              VARCHAR(20),
    changed_by_user_id      INTEGER,
    change_reason           VARCHAR(500),
    notes                   TEXT,
    changed_at              TIMESTAMP       NOT NULL DEFAULT NOW()
);

INSERT INTO denial_reason_codes (code, carc_code, description) VALUES ('NO_AUTH', '197', 'Prior authorization required but absent');
INSERT INTO denial_reason_codes (code, carc_code, description) VALUES ('NO_REFERRAL', '37', 'Referral required but absent');
