-- H2 test stub for Phase 5 Slice 1 migration.
-- Omits PL/pgSQL triggers; uses IDENTITY PKs.

CREATE TABLE info_requests (
    id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id                INTEGER         NOT NULL REFERENCES claims(id),
    requested_from          VARCHAR(10)     NOT NULL,
    requested_by_user_id    INTEGER         NOT NULL REFERENCES users(id),
    requested_at            TIMESTAMP       NOT NULL DEFAULT NOW(),
    due_date                DATE            NOT NULL,
    request_notes           TEXT            NOT NULL,
    response_received_at    TIMESTAMP,
    response_notes          TEXT,
    status                  VARCHAR(10)     NOT NULL DEFAULT 'OPEN',
    created_at              TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE claim_notes (
    id              INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id        INTEGER         NOT NULL REFERENCES claims(id),
    author_user_id  INTEGER         NOT NULL REFERENCES users(id),
    note            TEXT            NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE sla_breaches (
    id          INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id    INTEGER         NOT NULL REFERENCES claims(id),
    status      VARCHAR(20)     NOT NULL,
    expected_by TIMESTAMP       NOT NULL,
    breached_at TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE phi_access_log (
    id          INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER         REFERENCES users(id),
    member_id   INTEGER         NOT NULL REFERENCES members(id),
    claim_id    INTEGER         NOT NULL REFERENCES claims(id),
    action      VARCHAR(30)     NOT NULL,
    accessed_at TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- No test V7 stub exists (test V6 already reflects the post-V7 end-state).
-- Flyway picks up V8 after V6 in test; no outOfOrder flag needed.
