-- H2 test stub for Phase 5 Slice 2 migration.
-- Omits PL/pgSQL triggers; uses IDENTITY PKs; DECIMAL for money (H2 dialect).

CREATE TABLE payments (
    id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id                INTEGER         NOT NULL REFERENCES claims(id),
    billed_total            DECIMAL(12,2)   NOT NULL,
    allowed_total           DECIMAL(12,2)   NOT NULL,
    plan_paid_total         DECIMAL(12,2)   NOT NULL,
    member_responsibility   DECIMAL(12,2)   NOT NULL,
    partial_payment_flag    BOOLEAN         NOT NULL DEFAULT FALSE,
    amount_paid             DECIMAL(12,2),
    remaining_balance       DECIMAL(12,2),
    reference_number        VARCHAR(100),
    status                  VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    payment_date            DATE,
    created_at              TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE eob_documents (
    id                  INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id            INTEGER         NOT NULL REFERENCES claims(id),
    member_id           INTEGER         NOT NULL REFERENCES members(id),
    content             TEXT            NOT NULL,
    delivery_method     VARCHAR(10)     NOT NULL DEFAULT 'PENDING',
    delivered_at        TIMESTAMP,
    mailed_by_user_id   INTEGER         REFERENCES users(id),
    generated_at        TIMESTAMP       NOT NULL DEFAULT NOW(),
    created_at          TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE remittance_batches (
    id              INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_date    DATE            NOT NULL,
    total_paid      DECIMAL(12,2)   NOT NULL,
    status          VARCHAR(20)     NOT NULL DEFAULT 'GENERATED',
    generated_at    TIMESTAMP       NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMP       NOT NULL DEFAULT NOW()
);

CREATE TABLE remittance_batch_items (
    id                      INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                INTEGER         NOT NULL REFERENCES remittance_batches(id),
    claim_id                INTEGER         NOT NULL REFERENCES claims(id),
    provider_id             INTEGER         NOT NULL REFERENCES providers(id),
    billed                  DECIMAL(12,2)   NOT NULL,
    allowed                 DECIMAL(12,2)   NOT NULL,
    plan_paid               DECIMAL(12,2)   NOT NULL,
    adjustment_reason_code  VARCHAR(50),
    created_at              TIMESTAMP       NOT NULL DEFAULT NOW()
);
